### ISSUE TITLE
Add a switch to exclude taskwarrior task annotations from the text displayed

### ISSUE THREAD

**Issue by grovesteyn** [garykl/task2dot#6]
This will give the user the ability to avoid the clutter from tasks with long annotations added to them.

**Comment by garykl** [comment]
Thanks for your suggestion! Here you are.

**Comment by garykl** [comment]
Just in case: Annotations are now suppressed by adding the option --annotation. This is now also described in the README.md.

**Comment by grovesteyn** [comment]
Brilliant - thanks!
